[connections.snowflake]
account = "FDVPRUS-JUB14161"
user = "WELLINGTONTI"
password = "Nunca24072301pq"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
